language: csharp
solution: src/EpicoinTerm/EpicoinTerm.sln
mono:
  - latest
script:    
  - git pull
  - git fetch --all
  - echo "Build Test"
  - make
  - make dependency
  - make build
  
  - echo "NUNIT Test"
  
